
export enum ROOM_ACTION_TYPES {
  CREATE_ROOM = "CREATE_ROOM",
  UPDATE_ROOM = "UPDATE_ROOM",
  DELETE_ROOM = "DELETE_ROOM",
  FETCH_ALL_ROOM = "FETCH_ALL_ROOM",
  FETCH_TRASH_ROOMS = "FETCH_TRASH_ROOMS",
  FETCH_BY_ID_ROOM = "FETCH_BY_ID_ROOM",
  FETCH_ROOM = "FETCH_ROOM",
  FETCH_ROOM_BYID = "FETCH_ROOM_BYID",
  MULTIHARD_DELETE_ROOM = "MULTIHARD_DELETE_ROOM",
  MULTISOFT_DELETE_ROOM = "MULTISOFT_DELETE_ROOM",
  MULTI_RECOVER_ROOM = "MULTI_RECOVER_ROOM",
  SINGLE_RECOVER_ROOM = "SINGLE_RECOVER_ROOM",
}

export enum HOTEL_ACTION_TYPES {
  CREATE_HOTEL = "CREATE_HOTEL",
  UPDATE_HOTEL = "UPDATE_HOTEL",
  DELETE_HOTEL = "DELETE_HOTEL",
  FETCH_ALL_HOTEL = "FETCH_ALL_HOTEL",
  FETCH_TRASH_HOTELS = "FETCH_TRASH_HOTELS",
  FETCH_BY_ID_HOTEL = "FETCH_BY_ID_HOTEL",
  FETCH_HOTEL = "FETCH_HOTEL",
  FETCH_HOTEL_BYID = "FETCH_HOTEL_BYID",
  MULTIHARD_DELETE_HOTEL = "MULTIHARD_DELETE_HOTEL",
  MULTISOFT_DELETE_HOTEL = "MULTISOFT_DELETE_HOTEL",
  MULTI_RECOVER_HOTEL = "MULTI_RECOVER_HOTEL",
  SINGLE_RECOVER_HOTEL = "SINGLE_RECOVER_HOTEL",
}
